all:
	scons
	echo Running twice is required to make good table of contents.
compare:
	../../tools/gen_cmp.sh
diffs:
	../../tools/gen_diff.sh
clean:
	rm -rf build .tmp_* log_b[12].txt pyconbook-????.log pyconbook-????.pdf *.pyc .sconsign.dblite genart.txt
