#!/usr/bin/env python2
# -*- coding: UTF-8 -*-
# Get articles and directories list

import os
import glob
import time

import pl_txt

created_pdf = time.strftime("pyconbook-%Y.pdf")
verbose = 1
if os.getenv('PLAIN'):
    create_pdfs = 0
    omit_diffs = 1
else:
    create_pdfs = 1
    omit_diffs = 0

tty_columns = os.getenv('COLUMNS')
if tty_columns:
    tty_columns = int(tty_columns)

copy_images = 1
only_first_article_for_testing = 0

if 'TEXINPUTS' not in os.environ:
    os.environ['TEXINPUTS']=''
os.environ['TEXINPUTS'] = (
    ".:..:../..:../../sty:" +
    os.environ['TEXINPUTS'] )
env = Environment(ENV=os.environ)

genart_file = 'genart.txt'
build_dir = "build"

def prepare_art(artlist_file):
    al_loc_ls = []
    for line in open(artlist_file):
        line = pl_txt.remove_comments(line)
        words = line.split()
        if words:
            alias, location = words[:2]
            al_loc_ls.append([alias, location])

    if only_first_article_for_testing:
        al_loc_ls = al_loc_ls[:1]

    selected = os.getenv('SELECTED')
    if selected:
        sel_ls = selected.split()
        al_loc_ls = filter(lambda x: x[0] in sel_ls, al_loc_ls)
    return al_loc_ls

al_loc_ls = prepare_art('artlist.txt')
new_data = pl_txt.prepare_file(al_loc_ls)
pl_txt.write_if_needed(genart_file, new_data)

final_pdfs = map(
    (lambda x: "{}/{}/{}.pdf".format(build_dir, x[0], x[0])),
    al_loc_ls)

pl_txt.env_command(
    env,
    created_pdf,
    final_pdfs,
    "texexec --pdfcopy --result=$TARGET $SOURCES",
    )

for alias, location in al_loc_ls:
    txt_line = pl_txt.prepare_line(tty_columns, alias, location)
    root = "{}/{}/{}".format(build_dir, alias, alias)
    src_ls = (
        [
            root + ".tex",
            genart_file,
            build_dir + "/artpages.inc",
            ] +
        glob.glob("sty/*") +
        glob.glob("src/" + alias + "/*"))
    small_pdf_ls = [
            "pwd",
            "# " + txt_line,
            pl_txt.link_src(alias),
            ]
    if copy_images:
        small_pdf_ls.append(
            "[ ${TARGET.file} != async.pdf ] || cp ../../../presentations/async_pod_maska/yield_from.png .",
            )
        small_pdf_ls.append(
            "[ ${TARGET.file} != microservices.pdf ] || cp ../../../presentations/tdd_of_python_microservices/fixtures.png .",
            )
        small_pdf_ls.append(
            "[ ${TARGET.file} != microservices.pdf ] || cp ../../../presentations/tdd_of_python_microservices/test_pyramid.png .",
            )
        small_pdf_ls.append(
            "[ ${TARGET.file} != microservices.pdf ] || cp ../../../presentations/tdd_of_python_microservices/tdd_cycle.png .",
            )
    if create_pdfs:
        small_pdf_ls.append("texexec --pdf " + alias)
    small_pdf_ls.append("mv artpages.inc .. 2>/dev/null || true")
    pl_txt.env_command(
        env,
        root + ".pdf",
        src_ls,
        small_pdf_ls,
        chdir = "%s/%s" % (build_dir, alias),
        )
    loc_src  = "src/" + alias + "/text.tex"
    main_src = "../" + location + "/text.tex"
    main_md  = "../" + location + "/text.md"
    diffsrc  = glob.glob("src/" + alias + ".diff")
    if verbose:
        print "Checking '%s' in:" % alias
        print loc_src
        print main_src
        print main_md
    if os.path.exists(loc_src):
        if verbose:
            print 'Found:', loc_src
        pl_txt.env_command(
            env,
            root + ".tex",
            loc_src,
            Copy('$TARGET','$SOURCE'),
            )
    elif os.path.exists(main_src):
        if verbose:
            print 'Found:', main_src
        pl_txt.env_command(
            env,
            root + ".tex",
            main_src,
            Copy('$TARGET','$SOURCE'),
            )
    elif os.path.exists(main_md):
        if verbose:
            print 'Found:', main_md
        pandoc_patch_ls = [
            Delete(".tmp"),
            Mkdir(".tmp"),
            pl_txt.run_pandoc(main_md),
            ]
        if diffsrc:
            pandoc_patch_ls.append(
                pl_txt.apply_patch(diffsrc, test_mode=omit_diffs)
                )
        pandoc_patch_ls.append(
            Copy("$TARGET", ".tmp/${TARGET.file}")
            )
        pl_txt.env_command(
            env,
            root + ".tex",
            [main_md] + diffsrc + Glob("src/*.inc.tex"),
            pandoc_patch_ls,
           )
    else:
        if verbose:
            print "Full path:", os.path.abspath(main_md)
        raise RuntimeError("Not found: %s" % repr(main_md))


pl_txt.env_command(
    env,
    "build/artpages.inc",
    [],
    [],
    )

# Local Variables:
# mode: python
# End:
